const fs=require('node:fs'),path=require('node:path');
const root=path.join(__dirname,'..');
const d=JSON.parse(fs.readFileSync(path.join(root,'seating-data.json')));
const M=require('../model.js');
const lines=[
'RECEPTION SEATING REVIEW — MEIGHAN & ERIC — OCTOBER 10, 2026',
'Updated '+d.updated,
'Live review: https://ericvav-collab.github.io/wedding-seating-chart/',
'',
'119 guests: 25 at the head table; 94 in 14 separate guest groups.',
'Meals: 74 beef (O), 33 chicken (C), 3 vegetarian (V), 1 vegan (VG), 8 needed (?).',
'Jason and Haley have beef. Miranda is vegan. Quan is not attending.',
'Natalia and Stella have no reception seats. Joe and Diane Messina are unseated maybes.',
'',
'LAYOUT OPTIONS — PROPOSALS TO MEASURE',
'B is the first option to measure: four joined 6-ft head-table sections,',
'12 seats on each long side plus Oliver at the south end. 25 head seats.',
'Opposite-side guests face Eric and Meg and turn to watch the stage.',
'',
'A: Double-sided U — 8 head-table sections, 13 guest rounds, 2 A&M sections.',
'   Total 10 six-foot banquet tables; preserves the U but takes more room.',
'B: Straight double-sided head — 4 head sections, 13 rounds, 2 A&M sections.',
'   Total 6 six-foot banquet tables; smallest head-table footprint.',
'C: Straight head; Tables 3, 5, 7, 11, 12, 14 each get their own 6-ft table.',
'   Total 12 six-foot banquet tables and 7 rounds. No groups are combined.',
'Cake uses a separate low table; boba uses a cart. Actual sizes to confirm.',
'All rounds have at most 8 guests. A&M alone has a 10-person, 12-ft table.',
'',
'SCALE AND SPACING',
'The vendor PDF supplies room proportions, with NO measured wall lengths',
'or scale bar. The earlier 38 x 48-ft true-scale claim is withdrawn.',
'The website offers hypothetical test sizes, not asserted room measurements.',
'The central Monza proportions are approximately 520:635 (width:depth).',
'Models assume 60-inch rounds, 6 x 2.5-ft banquet sections, a 2-ft chair',
'allowance and a 3-ft target gap between occupied chair spaces.',
'Smaller test sizes have conflicts. Even the default 54 x 65.9-ft test has',
'gaps below that target. No option is a confirmed physical fit yet.',
'Confirm wall lengths, stage, doors, chair pull-out, table supports,',
'serving routes, actual furniture and contracted lobby access with Milano.',
'',
'VENUE AND ORIENTATION',
'Stage LEFT; head table RIGHT; Eric NORTH/top; Meg SOUTH/bottom.',
'Planning directions match in all diagrams, not a surveyed compass bearing.',
'Dance floor attaches to stage. Keep the centre free of guest/cake tables.',
'Parents Tables 1 and 7 are toward the head-table end.',
'Front lobby: vendor bar position, proposed jazz trio in opposite pocket.',
'Keep the building entrance, Alba doorway and route to Monza open.',
'Boba: proposed in the front-lobby Monza entry recess; confirm queue space.',
'Cake: stage wall, Eric/top side. Reception band remains on the stage.',
'Photo booth: proposed rear lobby; confirm that this space is included.',
'Doria, Alba, patio, suite, corridor, restrooms and catering shown for context.',
'',
'HEAD SEATS — OPTION B/C (see website for option A)',
'Wall row, north to south, facing stage:',
...d.groups[0].guests.slice(0,12).map((g,i)=>` ${i+1}. ${g.name} (${g.meal})`),
'Opposite row, north to south, facing the couple:',
...d.groups[0].guests.slice(12,24).map((g,i)=>` ${i+13}. ${g.name} (${g.meal})`),
' 25. Oliver (O) — south end, next to James and near MM.',
'Eric and Meg are centred; Andrew V. is next to Eric, Mabelle next to Meg.',
'',
'GUEST GROUPS — EVERY OPTION',
...d.groups.slice(1).flatMap(t=>[
`TABLE ${t.id.slice(1)} — ${t.label} — ${t.guests.length} guests — ${t.flowers}`,
...t.guests.map((g,i)=>` ${i+1}. ${g.name} (${g.meal})`),'']),
'Sam and Adelia share the west corner of A&M; Danielle and Matt share the east corner.',
'FLORALS: 2 large (Tables 1,7), 4 compotes, 6 taper trios, head garland, A&M runner.',
'Table 14 needs an additional treatment. Confirm the inventory with the florist.',
'',
'MEALS NEEDED: '+d.groups.flatMap(t=>t.guests).filter(g=>g.meal==='?').map(g=>g.name).join(', '),
'',
'Sources: vendor Floorplan.pdf (architecture); guest list 083026.csv (courses);',
'Eric’s corrections through September 6. Coaster order maintained separately.',
''];
fs.writeFileSync(path.join(root,'seating-review.txt'),lines.join('\n'));
console.log('Current review copy generated.');
